# Task solution to execute
string container
float32 pouring_time
---

# Result of execution
ManipulationResult result

---

# Error result
moveit_msgs/MoveItErrorCodes error_code

---

# current stage/subtrajectory during execution
string state